workflows:
  android-app-build:
    name: Android App Build
    environment:
      android_sdk_version: '34'
      java_version: '17'
    scripts:
      - name: Build Android Release
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
