workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android release
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
